# Generated by Django 3.2.9 on 2021-11-29 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='student',
            fields=[
                ('reg_num', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('degree', models.CharField(choices=[('1', 'BS-CS'), ('2', 'BS-civil')], max_length=1)),
            ],
        ),
    ]
